setwd("E:/Multivariate II/Data")
x=read.table("aphanius.txt")
x=read.table("E:\\Multivariate II\\Data\\aphanius.txt")
x<- read.delim("E:/Multivariate II/Data/aphanius.txt", header=FALSE)
names(x)=c("X1","X2","X3","X4","X5")
d=dist(x,method="euclidean")
m1=hclust(d,method="single")
m2=hclust(d,method="complete")
m3=hclust(d,method="average")
X11()
par(mfrow=c(3,1))
plot(m1);plot(m2);plot(m3)

X11()
par(mfrow=c(3,1))
plot(m1) 
groups <- cutree(m1, k=4) 
rect.hclust(m1, k=4, border="red")
plot(m2) 
groups <- cutree(m2, k=4)
rect.hclust(m2, k=4, border="red")
plot(m3) 
groups <- cutree(m3, k=4) 
rect.hclust(m3, k=4, border="red")
