setwd("E:/Multivariate II/Data")
x=read.table("aphanius.txt")
x=read.table("E:\\Multivariate II\\Data\\aphanius.txt")
x<- read.delim("E:/Multivariate II/Data/aphanius.txt", header=FALSE)
names(x)=c("X1","X2","X3","X4","X5")
d=dist(x,method="euclidean")
print(d,digits=2)
set.seed(1)
m=kmeans(x,4, algorithm = "MacQueen")
d1=dist(m$centers,method="euclidean")
wss <- (nrow(x)-1)*sum(apply(x,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(x,centers=i)$withinss)
X11()
plot(1:15, wss, type="b", xlab="Number of Clusters",ylab="Within groups sum of squares")
aggregate(x,by=list(m$cluster),FUN=mean)
Datacl <- data.frame(x, m$cluster)
Datacl
library(cluster)
X11()
clusplot(x, m$cluster, color=TRUE, shade=TRUE,labels=2, lines=0)
library(fpc)
X11()
plotcluster(x, m$cluster)
